#!/usr/bin/env node
/**
 * Bake a 12×12 grid of average colours for every artwork so undiscovered pieces
 * can be drawn as crisp pixel blocks (see src/components/Mosaic.tsx).
 *
 *   npm i -D jimp
 *   node scripts/pixelate.mjs
 *
 * Why: iOS smooths any upscaled bitmap, so a small image reads as "blurred",
 * not "pixelated". Baking the colours lets us draw hard-edged rectangles — and
 * undiscovered pieces then need no image download at all (faster + cooler).
 *
 * Safe to re-run: only processes ids that aren't baked yet.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Jimp from 'jimp';
import { IMAGE_OVERRIDES } from './overrides.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const ARTWORKS_TS = path.join(root, 'src/data/artworks.ts');
const IMAGES_TS = path.join(root, 'src/data/images.ts');
const OUT_TS = path.join(root, 'src/data/mosaics.ts');

const N = 12; // grid size — must match MOSAIC_N in Mosaic.tsx
const SAMPLE_WIDTH = 96; // download this small, then downsample
const DELAY_MS = 300; // gentle: Wikimedia throttles rapid thumbnail requests
const MAX_RETRIES = 5;
const UA = 'QArt/1.0 (personal art app; educational use)';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
let rateLimitStreak = 0;

function loadIds() {
  const src = fs.readFileSync(ARTWORKS_TS, 'utf8');
  return [...src.matchAll(/\{ id: "([^"]+)"/g)].map((m) => m[1]);
}
function loadKV(file) {
  if (!fs.existsSync(file)) return {};
  const map = {};
  const re = /"([^"]+)":\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(fs.readFileSync(file, 'utf8')))) map[m[1]] = m[2];
  return map;
}

function sizedUrl(url, w) {
  if (!url) return url;
  if (url.includes('Special:FilePath/')) return url.replace(/\?.*$/, '') + `?width=${w}`;
  const m = url.match(/upload\.wikimedia\.org\/wikipedia\/commons\/(?:thumb\/)?[0-9a-f]\/[0-9a-f]{2}\/([^/?]+)/);
  if (m) return `https://commons.wikimedia.org/wiki/Special:FilePath/${m[1]}?width=${w}`;
  return url;
}


// Fetch with retry/backoff — without this, one 429 from Wikimedia and the whole
// run collapses into failures (which is exactly what happened the first time).
async function fetchBuffer(url) {
  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': UA } });
      if (res.status === 429 || res.status === 503) {
        rateLimitStreak++;
        await sleep(Math.min(1500 * (attempt + 1), 8000) + (rateLimitStreak > 5 ? 20000 : 0));
        continue;
      }
      rateLimitStreak = Math.max(0, rateLimitStreak - 1);
      if (!res.ok) return { err: `HTTP ${res.status}` };
      return { buf: Buffer.from(await res.arrayBuffer()) };
    } catch (e) {
      await sleep(900 * (attempt + 1));
    }
  }
  return { err: 'throttled (gave up after retries)' };
}

async function mosaicFor(url) {
  const { buf, err } = await fetchBuffer(sizedUrl(url, SAMPLE_WIDTH));
  if (err) throw new Error(err);
  const img = await Jimp.read(buf);
  // Average down to the colour grid, then blow it back up with nearest-neighbour
  // so the blocks stay hard-edged. Baking the picture means the app renders ONE
  // image instead of ~144 SVG rectangles per tile (that was cooking the phone).
  img.resize(N, N);
  img.resize(N * 16, N * 16, Jimp.RESIZE_NEAREST_NEIGHBOR);
  return await img.getBase64Async(Jimp.MIME_PNG);
}

function write(map) {
  const entries = Object.keys(map)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(map[id])},`)
    .join('\n');
  fs.writeFileSync(
    OUT_TS,
    `// Baked 12×12 colour grids used to render undiscovered pieces as crisp
// pixelated blocks (no image download needed).
// Generated by scripts/pixelate.mjs — do not edit by hand.
//
// Each value is 144 concatenated 3-char hex colours, row-major.

export const MOSAICS: Record<string, string> = {\n${entries}\n};\n`,
    'utf8'
  );
}

async function main() {
  const ids = loadIds();
  const images = loadKV(IMAGES_TS);
  const mosaics = loadKV(OUT_TS);
  // Re-bake anything missing, plus legacy hex-grid entries from the old format.
  // With REBAKE_OVERRIDES=1, also refresh the pixelation of hand-mapped pieces
  // whose image was swapped (otherwise their locked preview stays the old art).
  const REBAKE_OVERRIDES = process.env.REBAKE_OVERRIDES === '1';
  const overrideIds = new Set(Object.keys(IMAGE_OVERRIDES));
  const todo = ids.filter(
    (id) =>
      images[id] &&
      (!(mosaics[id] || '').startsWith('data:') || (REBAKE_OVERRIDES && overrideIds.has(id)))
  );

  console.log(`Artworks with an image: ${ids.filter((i) => images[i]).length} · already baked: ${Object.keys(mosaics).length} · to do: ${todo.length}\n`);
  if (!todo.length) return console.log('Nothing to do.');

  let done = 0;
  const reasons = {};
  for (const id of todo) {
    try {
      const grid = await mosaicFor(images[id]);
      if (grid) mosaics[id] = grid;
      else reasons['empty result'] = (reasons['empty result'] ?? 0) + 1;
    } catch (e) {
      const why = String(e?.message ?? e).slice(0, 60);
      reasons[why] = (reasons[why] ?? 0) + 1;
    }
    done++;
    const failed = Object.values(reasons).reduce((a, b) => a + b, 0);
    process.stdout.write(`  ${done}/${todo.length} (${failed} failed)\r`);
    if (done % 20 === 0) write(mosaics);
    await sleep(DELAY_MS);
  }
  write(mosaics);

  const failed = Object.values(reasons).reduce((a, b) => a + b, 0);
  console.log(`\n\nBaked ${Object.keys(mosaics).length} mosaics into src/data/mosaics.ts.`);
  if (failed) {
    console.log(`\n${failed} failed — reasons:`);
    for (const [why, n] of Object.entries(reasons).sort((a, b) => b[1] - a[1])) {
      console.log(`  ${String(n).padStart(4)}  ${why}`);
    }
    console.log('\nRe-run to retry just the missing ones.');
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
